# Generated by Django 2.2.4 on 2019-08-04 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import social_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='files/default_avatar.jpg', upload_to=social_app.models.get_user_image)),
                ('institute', models.CharField(max_length=60)),
                ('age', models.IntegerField(default=-1)),
                ('bio', models.TextField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=500)),
                ('input_file', models.FileField(upload_to=social_app.models.get_user_post_dir)),
                ('output_file', models.FileField(null=True, upload_to=social_app.models.get_user_post_dir)),
                ('created_at', models.DateTimeField()),
                ('likes', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=750)),
                ('created_at', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social_app.Post')),
            ],
        ),
    ]
