# Generated by Django 2.2.4 on 2019-08-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Finished', 'Finshed'), ('Failed', 'Failed'), ('Processing', 'Processing'), ('Started', 'Started')], max_length=20)),
                ('created_at', models.DateField()),
                ('modified_at', models.DateField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_app.Post')),
            ],
        ),
    ]
